name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pipeline:
    name: CI/CD Pipeline
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt pytest pytest-flask pytest-mock

    - name: Run tests
      run: |
        export PYTHONPATH=$(pwd)
        pytest

    - name: Run deploy script
      run: |
        chmod +x deploy.sh
        ./deploy.sh

    - name: Wait for deployment
      run: sleep 10

    - name: Verify deployment
      run: |
        curl -f http://localhost:5000/metrics
